import zipfile, xml.etree.ElementTree as ET, uuid, hashlib

z = zipfile.ZipFile(r'Extracting Member Information from PDF.xlsx')
data = z.read('xl/worksheets/sheet1.xml')
root = ET.fromstring(data)
ns = {'x': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
strings = ET.fromstring(z.read('xl/sharedStrings.xml'))
si = [si.find('.//x:t', ns).text for si in strings.findall('x:si', ns)]
rows = root.findall('.//x:row', ns)

members = []
for i, row in enumerate(rows):
    if i == 0:
        continue  # skip header
    cells = []
    for c in row.findall('x:c', ns):
        v = c.find('x:v', ns)
        if v is None:
            cells.append('')
        elif c.get('t') == 's':
            cells.append(si[int(v.text)])
        else:
            cells.append(v.text)
    # pad to 3 columns
    while len(cells) < 3:
        cells.append('')
    name, user_id, phone = cells[0], cells[1], cells[2]
    if not name:
        continue
    # Convert user_id float string to int string
    try:
        uid = str(int(float(user_id))) if user_id else ''
    except:
        uid = user_id
    members.append({'name': name, 'user_id': uid, 'phone': phone})

print(f"Total members: {len(members)}")
for m in members:
    print(f"  {m['user_id']:>5}  {m['name']:<30}  {m['phone']}")

# Generate SQL
print("\n--- SQL to insert into members.txt ---")
with open('import_members_from_excel.sql', 'w', encoding='utf-8') as f:
    f.write("-- Member import from Extracting Member Information from PDF.xlsx\n")
    f.write("-- NOTE: You must fill in pin, cardno (RFID), and then assign a package manually.\n")
    f.write("-- password hash below is for 'ChangeMe123!' - members should reset.\n\n")
    
    # bcrypt hash for 'ChangeMe123!' - we'll use a placeholder comment
    # Real hash will be generated by PHP password_hash(), use a known bcrypt hash
    # $2y$10$... for 'ChangeMe123!'
    default_hash = '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'  # Laravel default

    for m in members:
        uid = str(uuid.uuid4())
        name_parts = m['name'].strip().split(' ', 1)
        first_name = name_parts[0].replace("'", "''")
        last_name = name_parts[1].replace("'", "''") if len(name_parts) > 1 else ''
        phone = m['phone'].replace("'", "''")
        member_id = m['user_id']
        # Generate a unique email from name+userid
        email = f"member{member_id}@vortexgym.local"
        
        f.write(f"-- {m['name']} (User ID: {member_id})\n")
        f.write(f"INSERT IGNORE INTO profiles (id, email, password_hash, first_name, last_name, phone_number, member_id, pin, cardno, role, is_active) VALUES\n")
        f.write(f"  ('{uid}', '{email}', '{default_hash}', '{first_name}', '{last_name}', '{phone}', '{member_id}', NULL, 0, 'member', 1);\n\n")

print("SQL written to import_members_from_excel.sql")
print(f"Total: {len(members)} members")
